### ISSUE TITLE
Missed closing parenthesis

### ISSUE THREAD

**Issue by ChameleonTartu** [M4t1ss/SoftAlignments#1]
https://github.com/M4t1ss/SoftAlignments/blob/master/web/functions.php#L56

I think that closing parenthesis "?>" is missed.

**Comment by M4t1ss** [comment]
>  If a file is pure PHP code, it is preferable to omit the PHP closing tag at the end of the file. This prevents accidental whitespace or new lines being added after the PHP closing tag, which may cause unwanted effects because PHP will start output buffering when there is no intention from the programmer to send any output at that point in the script. 

http://php.net/manual/en/language.basic-syntax.phptags.php
