### ISSUE TITLE
Fails if source string empty

### ISSUE THREAD

**Issue by bricksdont** [M4t1ss/SoftAlignments#22]
`processAlignments` currently fails if the source is empty and the only attention weights are `1.0`s on the `</s>` (=`<EOS>`) token.

```sh
$ cat test.a
0 ||| a test ||| 8.20928 ||| ||| 0 2
1.0
1.0
1.0
```

```sh
$ python ~/SoftAlignments/process_alignments.py -i test.a -f Nematus -o color
```

```python
Traceback (most recent call last):
  File "/home/user/mmueller/SoftAlignments/process_alignments.py", line 270, in <module>
    main(sys.argv[1:])
  File "/home/user/mmueller/SoftAlignments/process_alignments.py", line 252, in main
    functions.processAlignments(data, folder, inputfile, outputType, num, refs)
  File "/home/user/mmueller/SoftAlignments/functions.py", line 227, in processAlignments
    ali = [l[:len(list(filter(None, tgt)))] for l in rawAli[:len(src)]]
IndexError: invalid index to scalar variable.
```

Is this a bug / unaccounted-for edge case, or am I doing something wrong?

Having an empty source seems like a strange requirement, but I am working with multiple sources, so that's a real use case.

Thanks!

**Comment by M4t1ss** [comment]
Hmm... looks like a bug...
There should be two spaces between the two `|||` separators, because it splits by ' ||| ' 😆 
It does work with: 
```
0 ||| a test ||| 8.20928 |||  ||| 0 2
1.0 1.0
1.0 1.0
1.0 1.0
```
Gives me 
![image](https://user-images.githubusercontent.com/1122842/35357066-fcca66e6-015a-11e8-8e10-e797730e550a.png)

Can you please check if #23 fixes this?

**Comment by bricksdont** [comment]
Yes, together with two spaces in between the `|||` it works - thanks!
