### ISSUE TITLE
Maximum execution time exceeded

### ISSUE THREAD

**Issue by bricksdont** [M4t1ss/SoftAlignments#28]
Hi Matiss

For a very large alignments file (150 MB) I get the following error:

>Fatal error: Maximum execution time of 30 seconds exceeded in /Users/mathiasmuller/Desktop/alignments/SoftAlignments/web/functions.php on line 54

Is there anything I can do? It would be nice if the tool could load bigger files on demand, e.g. for the web version.

Thanks and regards!
Mathias

**Comment by M4t1ss** [comment]
Hi Mathias! 
A big file 😮 
Looks like a PHP thing here... For now, try adding 
> set_time_limit(0);

right after
> \<?php 

at the top of `functions.php`
It should allow for the script to execute until it's all done.
In case that fails, try also adding 
> ignore_user_abort();

in the same place...

**Comment by bricksdont** [comment]
Setting the time limit works thanks!
