### ISSUE TITLE
The option color and web display unclear and suggestion using more deep color.

### ISSUE THREAD

**Issue by XiaoqingNLP** [M4t1ss/SoftAlignments#36]
thank you for your work . if this option is convenient for you , you can consider my suggestion.

**Comment by M4t1ss** [comment]
If you are attending the MT Marathon next week (http://www.statmt.org/mtm19/programme.html) I can make them more clear in the tutorial on Tuesday 😃 
About the color - currently, it is one of 23 values from 232 to 255, where one end is completely black and the other - white. Not sure how to make them any deeper than black 🖤

**Comment by XiaoqingNLP** [comment]
> If you are attending the MT Marathon next week (http://www.statmt.org/mtm19/programme.html) I can make them more clear in the tutorial on Tuesday 😃

Why do you say that? Is there any deep meaning?


> About the color - currently, it is one of 23 values from 232 to 255, where one end is completely black and the other - white. Not sure how to make them any deeper than black 🖤

I got your meaning , it is my attention to scatter and display unclear. sometime it is will be more clear with more clear attention. 

I also show you my draw a attention picture and it display more colorful. Thank you for your kindness reply and your great work. 
![image](https://user-images.githubusercontent.com/12473617/63577034-164c4280-c5c0-11e9-8d54-565ac18f584a.png)
