### ISSUE TITLE
*suggestion* if this code support three or four system compare will be better ? 

### ISSUE THREAD

**Issue by XiaoqingNLP** [M4t1ss/SoftAlignments#38]
because this code support two system compare, it can adapt to support  compare three or four system compare.  researchers usually have multiply system to compare with same sentence.

**Comment by M4t1ss** [comment]
It could be done, but the alignments would be really messy if there were 3 (or more) stacked on top of each other 😄 
It may be useful to see the different outputs and their scores, as well as to browse through the data sets ...
If you can implement it, please do - pull requests are very welcome 😃 If you do work on that, I can help a little bit..
I'm not sure if I'll be doing this myself any time soon, though
